### PR TITLE
Android 9 API 28 CRASH Workaround Fix

### PR DESCRIPTION
**Pull request by jrsarath**
Manifest.xml mod for android 9 api28 support

### CODE REVIEW

**Comment by Suraj-Tiwari** [comment]
@jrsarath please resolve conflict

**Comment by jrsarath** [comment]
Done No need for user modifications, can work out of box

**Comment by jrsarath** [comment]
Hi, Merge Please ?

**Comment by Suraj-Tiwari** [comment]
Thanks for the PR.

**Pull request merged**
